#!/bin/sh

set -e
go mod tidy

# Run this script to format and lint the codebase
STAGED_GO_FILES=$(git diff --cached --name-status -- '*.go' | awk '$1 == "M" || $1 == "A" { print $2 }')
if [[ $STAGED_GO_FILES == "" ]]; then
	echo "no go files updated"
else
	for file in $STAGED_GO_FILES; do
		make fmt-one file=$file
		git add $file
	done
fi

make test
make linter
